name: Generate and Deploy API Docs

on:
  push:
    branches: [main]

jobs:
  generate-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install FastAPI dependencies
        run: |
          pip install -r backend-requirements.txt

      - name: Start FastAPI app in background
        run: |
          uvicorn back.main:app --host 127.0.0.1 --port 8000 &
          echo $! > uvicorn.pid
          sleep 5

      - name: Fetch OpenAPI spec
        run: |
          curl http://127.0.0.1:8000/openapi.json -o docs/openapi.json

      - name: Stop FastAPI app
        run: |
          kill $(cat uvicorn.pid)

      - name: Install MkDocs dependencies
        run: pip install -r requirements.txt

      - name: Deploy to GitHub Pages
        run: mkdocs gh-deploy --force
